; Installer strings (UTF-8 with BOM). English is the fallback language.

LangString NeedsWindows10 ${LANG_ENGLISH} "PPVPN requires 64-bit Windows 10 version 1809 or later."
LangString NeedsWindows10 ${LANG_SIMPCHINESE} "PPVPN 需要 64 位 Windows 10 1809 或更高版本。"
LangString SetupRunning ${LANG_ENGLISH} "PPVPN Setup is already running."
LangString SetupRunning ${LANG_SIMPCHINESE} "PPVPN 安装程序已在运行。"
LangString LicenseBottom ${LANG_ENGLISH} "PPVPN is free software under the GNU GPL, version 3 or later. You do not have to accept this license to install or use PPVPN. Click Next to continue."
LangString LicenseBottom ${LANG_SIMPCHINESE} "PPVPN 是自由软件，按 GNU GPL 第 3 版或更高版本发布。安装和使用 PPVPN 无需接受本许可。单击「下一步」继续。"
LangString TasksTitle ${LANG_ENGLISH} "Additional Tasks"
LangString TasksTitle ${LANG_SIMPCHINESE} "附加任务"
LangString TasksSubtitle ${LANG_ENGLISH} "Choose the additional tasks Setup should perform."
LangString TasksSubtitle ${LANG_SIMPCHINESE} "选择安装程序要执行的附加任务。"
LangString DesktopShortcut ${LANG_ENGLISH} "Create a &desktop shortcut"
LangString DesktopShortcut ${LANG_SIMPCHINESE} "创建桌面快捷方式(&D)"
LangString StoppingApp ${LANG_ENGLISH} "Closing PPVPN..."
LangString StoppingApp ${LANG_SIMPCHINESE} "正在关闭 PPVPN..."
LangString TerminatingApp ${LANG_ENGLISH} "Terminating PPVPN..."
LangString TerminatingApp ${LANG_SIMPCHINESE} "正在结束 PPVPN 进程..."
LangString StoppingAgent ${LANG_ENGLISH} "Closing the PPVPN notification agent..."
LangString StoppingAgent ${LANG_SIMPCHINESE} "正在关闭 PPVPN 通知助手..."
LangString StartingAgent ${LANG_ENGLISH} "Starting the PPVPN notification agent..."
LangString StartingAgent ${LANG_SIMPCHINESE} "正在启动 PPVPN 通知助手..."
LangString StoppingService ${LANG_ENGLISH} "Stopping the PPVPN network service..."
LangString StoppingService ${LANG_SIMPCHINESE} "正在停止 PPVPN 网络服务..."
LangString InstallingService ${LANG_ENGLISH} "Installing the PPVPN network service..."
LangString InstallingService ${LANG_SIMPCHINESE} "正在安装 PPVPN 网络服务..."
LangString ServiceInstallFailed ${LANG_ENGLISH} "The PPVPN network service could not be installed (error code $0). Setup will stop; please fix the problem and try again."
LangString ServiceInstallFailed ${LANG_SIMPCHINESE} "PPVPN 网络服务安装失败（错误码 $0）。安装程序将停止，请修复后重试。"
LangString RemovingService ${LANG_ENGLISH} "Removing the PPVPN network service..."
LangString RemovingService ${LANG_SIMPCHINESE} "正在移除 PPVPN 网络服务..."
LangString RemovingData ${LANG_ENGLISH} "Removing your PPVPN data..."
LangString RemovingData ${LANG_SIMPCHINESE} "正在删除你的 PPVPN 数据..."
LangString DataTitle ${LANG_ENGLISH} "Uninstall PPVPN"
LangString DataTitle ${LANG_SIMPCHINESE} "卸载 PPVPN"
LangString DataSubtitle ${LANG_ENGLISH} "Remove PPVPN from this computer."
LangString DataSubtitle ${LANG_SIMPCHINESE} "从这台电脑中移除 PPVPN。"
LangString DataExplain ${LANG_ENGLISH} "PPVPN and its network service will be removed from $INSTDIR.$\r$\n$\r$\nYour sign-in, settings and logs are kept, so they are still there if you install PPVPN again."
LangString DataExplain ${LANG_SIMPCHINESE} "将从 $INSTDIR 移除 PPVPN 及其网络服务。$\r$\n$\r$\n你的登录信息、设置和日志会保留，重新安装 PPVPN 后仍可使用。"
LangString DataRemove ${LANG_ENGLISH} "Also &remove my sign-in, settings and logs"
LangString DataRemove ${LANG_SIMPCHINESE} "同时删除我的登录信息、设置和日志(&R)"
