#!/usr/bin/env bash
# Build ppvpn-client for macOS (arm64 + x86_64) and emit a local SwiftPM
# package: Sources/PPVPNClient/*.swift + PPVPNClientFFI.xcframework, a
# dynamic framework (the app and its push agent share one copy in
# PPVPN.app/Contents/Frameworks; install name @rpath/PPVPNClientFFI.framework/...).
#
# Usage: scripts/build-apple.sh [output-dir] [--debug]
#   output-dir defaults to <repo>/apps/macos/PPVPNClient
set -euo pipefail

CRATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_DIR="$(cd "$CRATE_DIR/../.." && pwd)"
OUT_DIR="${1:-$REPO_DIR/apps/macos/PPVPNClient}"
PROFILE=release
[[ "${2:-}" == "--debug" ]] && PROFILE=debug
CARGO_FLAGS=(--locked)
[[ "$PROFILE" == release ]] && CARGO_FLAGS+=(--release)
TARGETS=(aarch64-apple-darwin x86_64-apple-darwin)
LIB=libppvpn_client.dylib
FRAMEWORK=PPVPNClientFFI
export MACOSX_DEPLOYMENT_TARGET=13.0

cd "$CRATE_DIR"
for target in "${TARGETS[@]}"; do
  rustup target add "$target" >/dev/null
  cargo build ${CARGO_FLAGS[@]+"${CARGO_FLAGS[@]}"} --lib --target "$target"
done

TARGET_DIR="$(cargo metadata --format-version 1 --no-deps | python3 -c 'import json,sys; print(json.load(sys.stdin)["target_directory"])')"
WORK="$TARGET_DIR/apple-package"
rm -rf "$WORK" && mkdir -p "$WORK/bindings"

# Bindings are generated from the compiled library so they always match it.
cargo run --locked --quiet --bin uniffi-bindgen -- generate \
  --library "$TARGET_DIR/aarch64-apple-darwin/$PROFILE/$LIB" \
  --language swift --out-dir "$WORK/bindings"

# Versioned macOS framework around the universal dylib.
FW="$WORK/$FRAMEWORK.framework"
mkdir -p "$FW/Versions/A/Headers" "$FW/Versions/A/Modules" "$FW/Versions/A/Resources"
lipo -create -output "$FW/Versions/A/$FRAMEWORK" \
  "$TARGET_DIR/aarch64-apple-darwin/$PROFILE/$LIB" \
  "$TARGET_DIR/x86_64-apple-darwin/$PROFILE/$LIB"
install_name_tool -id "@rpath/$FRAMEWORK.framework/Versions/A/$FRAMEWORK" "$FW/Versions/A/$FRAMEWORK"
# Local symbols only; the exported FFI stays.
if [[ "$PROFILE" == release ]]; then strip -x "$FW/Versions/A/$FRAMEWORK"; fi
cp "$WORK/bindings/$FRAMEWORK.h" "$FW/Versions/A/Headers/"
cat > "$FW/Versions/A/Modules/module.modulemap" <<MAP
framework module $FRAMEWORK {
    header "$FRAMEWORK.h"
    export *
}
MAP
cat > "$FW/Versions/A/Resources/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>$FRAMEWORK</string>
    <key>CFBundleIdentifier</key><string>com.peakpassvpn.ppvpn.client-ffi</string>
    <key>CFBundleName</key><string>$FRAMEWORK</string>
    <key>CFBundlePackageType</key><string>FMWK</string>
    <key>CFBundleShortVersionString</key><string>$(cargo metadata --format-version 1 --no-deps | python3 -c 'import json,sys; print(json.load(sys.stdin)["packages"][0]["version"])')</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>$MACOSX_DEPLOYMENT_TARGET</string>
</dict>
</plist>
PLIST
ln -s A "$FW/Versions/Current"
for item in "$FRAMEWORK" Headers Modules Resources; do ln -s "Versions/Current/$item" "$FW/$item"; done

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/Sources/PPVPNClient"
xcodebuild -create-xcframework -framework "$FW" -output "$OUT_DIR/$FRAMEWORK.xcframework" >/dev/null
cp "$WORK"/bindings/*.swift "$OUT_DIR/Sources/PPVPNClient/"

cat > "$OUT_DIR/Package.swift" <<'SWIFT'
// swift-tools-version:5.9
// Generated by crates/desktop/scripts/build-apple.sh; do not edit.
import PackageDescription

let package = Package(
    name: "PPVPNClient",
    platforms: [.macOS(.v13)],
    products: [.library(name: "PPVPNClient", targets: ["PPVPNClient"])],
    targets: [
        .binaryTarget(name: "PPVPNClientFFI", path: "PPVPNClientFFI.xcframework"),
        .target(
            name: "PPVPNClient",
            dependencies: ["PPVPNClientFFI"],
            linkerSettings: [.linkedFramework("SystemConfiguration"), .linkedFramework("Security")]
        ),
    ]
)
SWIFT

echo "PPVPNClient package written to $OUT_DIR"
