using System.ComponentModel;
using System.Runtime.InteropServices;
using CommunityToolkit.Mvvm.Input;
using H.NotifyIcon;
using H.NotifyIcon.Core;
using Microsoft.UI.Dispatching;
using Microsoft.Win32;
using PPVPN.App.Core.ViewModels;
using DrawingIcon = System.Drawing.Icon;

namespace PPVPN.Windows;

/// <summary>
/// Notification-area icon and menu, rendered from App.Core's <see cref="MainViewModel.Tray"/>
/// model (design §5, single "Connect" item). Icons: monochrome, shape only — off = outline,
/// busy = outline breathing (2 frames), on = solid, error = outline + "!" corner — in a
/// light-taskbar and a dark-taskbar set (Assets/Tray, generated by scripts/make-tray-icons.ps1),
/// picked by the taskbar theme. The menu is a native Win32 popup menu built on open with
/// H.NotifyIcon.Core's PopupMenu (the library's MenuFlyout conversion does not invoke item
/// commands with this SDK version). Win32 menus are single-line with no colours: the header is
/// one disabled line, secondary texts are right-aligned after a tab, the unread line has no red
/// dot, and the node submenu has no flags; it opens to the left by itself at the right edge.
/// </summary>
sealed class TrayIconHost : IDisposable
{
    readonly MainViewModel _vm;
    readonly TaskbarIcon _icon;
    readonly DispatcherQueueTimer _breathing;
    readonly global::Windows.UI.ViewManagement.UISettings _uiSettings = new();
    string? _shownFile;
    bool _frame;

    public TrayIconHost(MainViewModel vm)
    {
        _vm = vm;
        _icon = new TaskbarIcon
        {
            ToolTipText = "PPVPN",
            NoLeftClickDelay = true,
            LeftClickCommand = vm.OpenMainCommand,
            RightClickCommand = new RelayCommand(ShowMenu),
        };
        var dispatcher = DispatcherQueue.GetForCurrentThread();
        _breathing = dispatcher.CreateTimer();
        _breathing.Interval = TimeSpan.FromMilliseconds(700);
        _breathing.Tick += (_, _) =>
        {
            _frame = !_frame;
            UpdateIcon();
        };
        // The taskbar theme can change while we run.
        _uiSettings.ColorValuesChanged += (_, _) => dispatcher.TryEnqueue(UpdateIcon);
        Update();
        _icon.ForceCreate(enablesEfficiencyMode: false);
        vm.PropertyChanged += OnChanged;
    }

    /// <summary>SystemUsesLightTheme = 0: dark taskbar (white glyphs).</summary>
    static bool TaskbarIsLight()
    {
        try
        {
            using var key = Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize");
            return key?.GetValue("SystemUsesLightTheme") is int value && value != 0;
        }
        catch (Exception)
        {
            return false;
        }
    }

    void UpdateIcon()
    {
        var state = _vm.Tray.Icon;
        if (state == TrayIconState.Busy && !_breathing.IsRunning) _breathing.Start();
        else if (state != TrayIconState.Busy && _breathing.IsRunning) _breathing.Stop();
        var name = state switch
        {
            TrayIconState.On => "on",
            TrayIconState.Error => "error",
            TrayIconState.Busy => _frame ? "busy2" : "busy1",
            _ => "off",
        };
        var file = $"{(TaskbarIsLight() ? "light" : "dark")}-{name}.ico";
        if (file == _shownFile) return;
        var path = Path.Combine(AppContext.BaseDirectory, "Assets", "Tray", file);
        // TaskbarIcon takes ownership: it disposes the previous Icon when a new one is set.
        if (File.Exists(path)) _icon.Icon = new DrawingIcon(path);
        _shownFile = file;
    }

    void ShowMenu()
    {
        GetCursorPos(out var point);
        ShowMenuAt(point.X, point.Y);
    }

    /// <summary>Shows the menu at a screen point (also <c>--demo-tray</c>). Modal (TrackPopupMenu); click handlers run on this (UI) thread.</summary>
    public void ShowMenuAt(int x, int y)
    {
        var menu = new PopupMenu();
        foreach (var item in _vm.Tray.Items)
            if (Render(item) is { } rendered) menu.Items.Add(rendered);
        menu.Show(_icon.TrayIcon.WindowHandle, x, y);
    }

    static PopupItem? Render(TrayItem item)
    {
        var text = item.Secondary is { Length: > 0 } secondary
            ? item.Kind == TrayItemKind.Header ? $"{item.Text} · {secondary}" : $"{item.Text}\t{secondary}"
            : item.Text;
        switch (item.Kind)
        {
            case TrayItemKind.Separator:
                return new PopupMenuSeparator();
            case TrayItemKind.Header or TrayItemKind.Disabled:
                return new PopupMenuItem { Text = text, Enabled = false };
            case TrayItemKind.Submenu:
                var submenu = new PopupSubMenu(text);
                foreach (var child in item.Children ?? [])
                    if (Render(child) is { } rendered) submenu.Items.Add(rendered);
                return submenu;
            default:
                return new PopupMenuItem(text, (_, _) =>
                {
                    if (item.Command?.CanExecute(item.CommandParameter) == true) item.Command.Execute(item.CommandParameter);
                })
                {
                    Checked = item.IsChecked,
                    Enabled = item.IsEnabled,
                };
        }
    }

    void OnChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(MainViewModel.Tray)) Update();
    }

    void Update()
    {
        UpdateIcon();
        _icon.ToolTipText = _vm.Tray.ToolTip;
    }

    public void Dispose()
    {
        _breathing.Stop();
        _vm.PropertyChanged -= OnChanged;
        _icon.Dispose();
    }

    [StructLayout(LayoutKind.Sequential)]
    struct POINT
    {
        public int X;
        public int Y;
    }

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    static extern bool GetCursorPos(out POINT point);
}
