#!/usr/bin/env bash
# Build ppvpn-client for Linux and emit the PPVPNClient SwiftPM package that
# apps/macos/AppLogic depends on, so the app logic builds and tests on Linux
# (CI and Linux test machines; the macOS app uses build-apple.sh instead).
#
# Usage: apps/macos/scripts/build-swift-linux.sh [--release]
#        swift test --package-path apps/macos/AppLogic
#
# Writes apps/macos/PPVPNClient (git-ignored):
#   Sources/PPVPNClient/ppvpn_client.swift   UniFFI bindings
#   Sources/PPVPNClientFFI/                  header + module map
#   lib/libppvpn_client.so                   linked with an rpath to lib/
set -euo pipefail

[[ "$(uname -s)" == Linux ]] || { echo "build-swift-linux.sh: Linux only; on macOS use build-apple.sh" >&2; exit 2; }

MACOS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_DIR="$(cd "$MACOS_DIR/../.." && pwd)"
CRATE_DIR="$REPO_DIR/crates/ppvpn-client"
OUT_DIR="$MACOS_DIR/PPVPNClient"
PROFILE=debug
CARGO_FLAGS=()
if [[ "${1:-}" == --release ]]; then
  PROFILE=release
  CARGO_FLAGS+=(--release)
fi

cd "$CRATE_DIR"
cargo build ${CARGO_FLAGS[@]+"${CARGO_FLAGS[@]}"} --locked --lib
TARGET_DIR="$(cargo metadata --format-version 1 --no-deps | python3 -c 'import json,sys; print(json.load(sys.stdin)["target_directory"])')"
# CARGO_BUILD_TARGET (CI sets it so that every build shares one target
# directory) puts the output under the triple.
LIB="$TARGET_DIR/${CARGO_BUILD_TARGET:+$CARGO_BUILD_TARGET/}$PROFILE/libppvpn_client.so"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
# Bindings are generated from the compiled library so they always match it.
cargo run ${CARGO_FLAGS[@]+"${CARGO_FLAGS[@]}"} --locked --quiet --bin uniffi-bindgen -- generate \
  --library "$LIB" --language swift --out-dir "$WORK"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/Sources/PPVPNClient" "$OUT_DIR/Sources/PPVPNClientFFI" "$OUT_DIR/lib"
cp "$WORK"/*.swift "$OUT_DIR/Sources/PPVPNClient/"
cp "$WORK"/*.h "$OUT_DIR/Sources/PPVPNClientFFI/"
cp "$LIB" "$OUT_DIR/lib/"
# The generated module map names Darwin modules; Linux needs a plain one.
# The module name comes from uniffi.toml (ffi_module_name).
MODULE="$(sed -n 's/^module \([A-Za-z0-9_]*\).*/\1/p' "$WORK"/*.modulemap | head -1)"
HEADER="$(basename "$WORK"/*.h)"
cat > "$OUT_DIR/Sources/PPVPNClientFFI/module.modulemap" <<MAP
module $MODULE {
    header "$HEADER"
    link "ppvpn_client"
    export *
}
MAP

cat > "$OUT_DIR/Package.swift" <<SWIFT
// swift-tools-version:5.10
// Generated by apps/macos/scripts/build-swift-linux.sh; do not edit.
import PackageDescription

let lib = "$OUT_DIR/lib"

let package = Package(
    name: "PPVPNClient",
    products: [.library(name: "PPVPNClient", targets: ["PPVPNClient"])],
    targets: [
        .systemLibrary(name: "$MODULE", path: "Sources/PPVPNClientFFI"),
        .target(
            name: "PPVPNClient",
            dependencies: ["$MODULE"],
            linkerSettings: [.unsafeFlags(["-L", lib, "-Xlinker", "-rpath", "-Xlinker", lib])]
        ),
    ]
)
SWIFT

echo "PPVPNClient package (Linux, $PROFILE) written to $OUT_DIR"
